version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  php:
    container_name: social-php-fpm
    build: ./images/php
    links:
      - mysql
    volumes:
      - ./www:/var/www
  mysql:
    container_name: social-mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: social
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: password